# Generated by Django 4.1.6 on 2023-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
